org.gradle.jvmargs=-Xmx2048M
loom.ignoreDependencyLoomVersionValidation=true
enabled_platforms=fabric,neoforge
archives_name=monobank
jupiterVersion=5.11.3
##
minecraft_version=1.21.1
minecraft_version_range=[1.21,)
supported_minecraft_versions=1.21,1.21.1
parchment_version=1.21.1:2024.11.17
## Mod Properties
mod_id=monobank
mod_name=Monobank
mod_version=1.2.0
mod_release_type=release
mod_license=MIT
mod_maven_group=io.github.mortuusars.monobank
mod_authors=mortuusars
mod_description=Your personal safe storage.
mod_page=https://www.curseforge.com/minecraft/mc-mods/monobank
mod_github=https://github.com/mortuusars/Monobank
mod_issues=https://github.com/mortuusars/Monobank/issues
mod_curseforge_project_id=817257
mod_modrinth_project_id=3bSjQuE3
# Fabric
fabric_loader_version=0.16.9
fabric_api_version=0.102.1+1.21.1
# NeoForge
neoforge_version=21.1.129
neoforge_version_range=[21,)
neoforge_loader_version_range=[4,)
# Dependencies
forge_config_api_port_version=21.1.0
mixinextras_version=0.4.1
# Mod Versions
thief_version=1.0.0
thief_version_range=[1.0.0,)
jei_version=19.19.0.220
jade_neoforge_id=6155158
# Create
create_version = 6.0.4-53
ponder_version = 1.0.46
flywheel_version = 1.0.2
registrate_version = MC1.21-1.3.0+62
